#!/usr/bin/env bun
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..')
const sourcePath = path.join(root, 'apps/sim/providers/models.ts')
const providerOrderPath = path.join(root, 'apps/sim/providers/utils.ts')
const outputPath = path.join(
  root,
  'apps/api/src/infrastructure/generated/base-provider-model-catalog.generated.ts'
)
const excludedProviders = new Set([
  'baseten',
  'fireworks',
  'litellm',
  'ollama',
  'ollama-cloud',
  'openrouter',
  'together',
  'vllm',
])

interface CatalogEntry {
  id: string
  provider: string
}

export function extractEntries(source: string, minimumEntries = 50): CatalogEntry[] {
  const entries: CatalogEntry[] = []
  let provider: string | undefined
  let readingModels = false

  for (const line of source.split(/\r?\n/)) {
    const providerMatch = /^ {2}(?:(['"])([^'"]+)\1|([A-Za-z0-9_-]+)): \{$/.exec(line)
    if (providerMatch) {
      provider = providerMatch[2] ?? providerMatch[3]
      readingModels = false
      continue
    }
    if (!provider) continue
    if (/^ {4}models: \[$/.test(line)) {
      readingModels = true
      continue
    }
    if (readingModels && /^ {4}\],?$/.test(line)) {
      readingModels = false
      continue
    }
    if (!readingModels || excludedProviders.has(provider)) continue
    const idMatch = /^ {8}id: (['"])(.*?)\1,?$/.exec(line)
    if (idMatch?.[2]) entries.push({ id: idMatch[2], provider })
  }

  if (entries.length < minimumEntries) {
    throw new Error(
      `Expected at least ${minimumEntries} base provider models, found ${entries.length}`
    )
  }
  return entries
}

export function extractProviderOrder(source: string): string[] {
  const providers: string[] = []
  let readingProviders = false

  for (const line of source.split(/\r?\n/)) {
    if (line.startsWith('export const providers:')) {
      readingProviders = true
      continue
    }
    if (!readingProviders) continue
    if (line === '}') break

    const providerMatch =
      /^ {2}(?:(['"])([^'"]+)\1|([A-Za-z0-9_-]+)): (?:buildProviderMetadata\(|\{)/.exec(line)
    const provider = providerMatch?.[2] ?? providerMatch?.[3]
    if (provider) providers.push(provider)
  }

  if (providers.length < 20) {
    throw new Error(`Expected at least 20 provider-order entries, found ${providers.length}`)
  }
  return providers
}

export function orderEntries(
  entries: readonly CatalogEntry[],
  providerOrder: readonly string[]
): CatalogEntry[] {
  const entriesByProvider = new Map<string, CatalogEntry[]>()
  for (const entry of entries) {
    const group = entriesByProvider.get(entry.provider) ?? []
    group.push(entry)
    entriesByProvider.set(entry.provider, group)
  }

  const ordered = providerOrder.flatMap((provider) => entriesByProvider.get(provider) ?? [])
  if (ordered.length !== entries.length) {
    const orderedProviders = new Set(providerOrder)
    const missing = [...entriesByProvider]
      .map(([provider]) => provider)
      .filter((provider) => !orderedProviders.has(provider))
    throw new Error(`Provider order is missing catalog providers: ${missing.join(', ')}`)
  }
  return ordered
}

function render(
  entries: readonly CatalogEntry[],
  sourceHash: string,
  providerOrderHash: string
): string {
  return `/** Generated by scripts/api/generate-base-provider-model-catalog.ts. */
export const BASE_PROVIDER_MODEL_SOURCE_SHA256 = '${sourceHash}' as const
export const BASE_PROVIDER_ORDER_SOURCE_SHA256 = '${providerOrderHash}' as const

export const baseProviderModelCatalog = ${JSON.stringify(entries, null, 2)} as const
`
}

async function main(): Promise<void> {
  const source = await readFile(sourcePath, 'utf8')
  const providerOrderSource = await readFile(providerOrderPath, 'utf8')
  const sourceHash = new Bun.CryptoHasher('sha256').update(source).digest('hex')
  const providerOrderHash = new Bun.CryptoHasher('sha256').update(providerOrderSource).digest('hex')
  const entries = orderEntries(extractEntries(source), extractProviderOrder(providerOrderSource))
  const output = render(entries, sourceHash, providerOrderHash)

  if (process.argv.includes('--check')) {
    const current = await readFile(outputPath, 'utf8').catch(() => '')
    if (current !== output) {
      throw new Error(
        'Base provider model catalog is stale; run bun scripts/api/generate-base-provider-model-catalog.ts'
      )
    }
    console.log(
      `Base provider model catalog is current (${sourceHash}; order ${providerOrderHash})`
    )
    return
  }

  await mkdir(path.dirname(outputPath), { recursive: true })
  await writeFile(outputPath, output)
  console.log(
    `Generated ${entries.length} base provider models (${sourceHash}; order ${providerOrderHash})`
  )
}

if (import.meta.main) {
  void main().catch((error) => {
    console.error(error instanceof Error ? error.stack : String(error))
    process.exit(1)
  })
}
