import { lazy, Suspense, useEffect, useState } from 'react'
import type {
  EditorBlockTemplateFieldV1,
  EditorBlockTemplateV1,
  EditorTemplateJsonValue,
} from '@sim/tool-catalog'
import type { EditorWorkflow } from './editor-api'
import { updateEditorSubBlockValue } from './editor-state'
import { loadEditorBlockTemplate } from './editor-templates'

const EditorStructuredField = lazy(() =>
  import('./editor-structured-field').then((module) => ({ default: module.EditorStructuredField }))
)
const EditorResourceField = lazy(() =>
  import('./editor-resource-field').then((module) => ({ default: module.EditorResourceField }))
)
const EditorDeepField = lazy(() =>
  import('./editor-deep-field').then((module) => ({ default: module.EditorDeepField }))
)

interface EditorBasicFieldsProps {
  blockId: string
  mode?: 'advanced' | 'basic' | 'all'
  onChange: (workflow: EditorWorkflow) => void
  onError: (message: string | null) => void
  workflow: EditorWorkflow
}

interface FieldControlProps {
  disabled: boolean
  field: EditorBlockTemplateFieldV1
  templateFields: EditorBlockTemplateFieldV1[]
  onError: (message: string | null) => void
  onValue: (value: EditorTemplateJsonValue) => void
  value: unknown
  workflow: EditorWorkflow
  blockId: string
}

const textTypes = new Set([
  'short-input',
  'credential-input',
  'oauth-input',
  'project-selector',
  'file-selector',
  'workflow-selector',
  'knowledge-base-selector',
  'folder-selector',
  'tag-selector',
  'user-selector',
  'channel-selector',
  'sheet-selector',
  'mcp-server-selector',
  'mcp-tool-selector',
  'document-selector',
  'table-selector',
  'column-selector',
])
const longTextTypes = new Set(['long-input', 'code'])
const numberTypes = new Set(['number-input', 'slider'])
const jsonTypes = new Set([
  'table',
  'checkbox-list',
  'grouped-checkbox-list',
  'messages-input',
  'variables-input',
  'input-mapping',
  'input-format',
  'response-format',
  'tool-input',
  'skill-input',
  'file-upload',
  'filter-builder',
  'router-input',
  'mcp-dynamic-args',
  'condition-input',
  'knowledge-tag-filters',
  'document-tag-entry',
  'sort-builder',
  'eval-input',
])
const structuredTypes = new Set([
  'condition-input',
  'document-tag-entry',
  'eval-input',
  'filter-builder',
  'input-format',
  'knowledge-tag-filters',
  'messages-input',
  'response-format',
  'router-input',
  'sort-builder',
  'variables-input',
])

function FieldControl({
  disabled,
  field,
  templateFields,
  onError,
  onValue,
  value,
  workflow,
  blockId,
}: FieldControlProps) {
  const serialized = typeof value === 'string' ? value : value == null ? '' : JSON.stringify(value)
  const [draft, setDraft] = useState(serialized)
  const [uploading, setUploading] = useState(false)
  const workspaceId = workflow.workspaceId ?? ''

  useEffect(() => {
    setDraft(serialized)
  }, [serialized])

  if (field.type === 'switch') {
    return (
      <input
        checked={value === true}
        disabled={disabled}
        onChange={(event) => onValue(event.target.checked)}
        type='checkbox'
      />
    )
  }
  if (
    field.selectorKey ||
    field.type === 'oauth-input' ||
    field.type === 'workflow-selector' ||
    field.type === 'knowledge-base-selector' ||
    field.type === 'table-selector' ||
    field.type === 'column-selector' ||
    field.type === 'mcp-server-selector' ||
    field.type === 'mcp-tool-selector'
  ) {
    return (
      <Suspense fallback={<small>Loading resource selector…</small>}>
        <EditorResourceField
          blockId={blockId}
          disabled={disabled}
          field={field}
          templateFields={templateFields}
          onError={onError}
          onValue={onValue}
          value={value}
          workflow={workflow}
        />
      </Suspense>
    )
  }
  if (
    field.type === 'table' ||
    field.type === 'tool-input' ||
    field.type === 'skill-input' ||
    field.type === 'input-mapping' ||
    field.type === 'mcp-dynamic-args'
  ) {
    return (
      <Suspense fallback={<small>Loading visual builder…</small>}>
        <EditorDeepField
          blockId={blockId}
          disabled={disabled}
          field={field}
          onError={onError}
          onValue={onValue}
          value={value}
          workflow={workflow}
        />
      </Suspense>
    )
  }
  if (field.type === 'text' || field.type === 'schedule-info') {
    return <small>This field is generated by the workflow runtime.</small>
  }
  if (field.type === 'file-upload') {
    return (
      <div className='editor-file-upload'>
        <input
          disabled={disabled || uploading || !workspaceId}
          multiple={field.multiple}
          onChange={(event) => {
            const files = Array.from(event.target.files ?? [])
            if (files.length === 0) return
            setUploading(true)
            void import('./attachment-upload')
              .then(({ uploadAttachments }) => uploadAttachments(files, workspaceId))
              .then(({ attachments, errors }) => {
                if (errors.length > 0) onError(errors.join('; '))
                if (attachments.length === 0) return
                const uploaded = attachments.map((attachment) => ({
                  id: attachment.id,
                  key: attachment.key ?? '',
                  name: attachment.filename,
                  path: attachment.path ?? '',
                  size: attachment.size,
                  type: attachment.mediaType,
                }))
                onValue(field.multiple ? uploaded : uploaded[0])
              })
              .catch((caught) => {
                onError(caught instanceof Error ? caught.message : 'Upload failed')
              })
              .finally(() => setUploading(false))
          }}
          type='file'
        />
        <small>{uploading ? 'Uploading…' : serialized || 'No file selected'}</small>
      </div>
    )
  }
  if (
    (field.type === 'dropdown' ||
      field.type === 'combobox' ||
      field.type === 'checkbox-list' ||
      field.type === 'grouped-checkbox-list') &&
    field.options &&
    field.options.length > 0
  ) {
    if (
      field.multiple ||
      field.type === 'checkbox-list' ||
      field.type === 'grouped-checkbox-list'
    ) {
      const selected = Array.isArray(value) ? value.map(String) : []
      return (
        <select
          disabled={disabled}
          multiple
          onChange={(event) =>
            onValue(Array.from(event.target.selectedOptions, (option) => option.value))
          }
          value={selected}
        >
          {field.options.map((option) => (
            <option key={option.id} value={option.id}>
              {option.label}
            </option>
          ))}
        </select>
      )
    }
    return (
      <select
        disabled={disabled}
        onChange={(event) => onValue(event.target.value)}
        value={serialized}
      >
        {!serialized ? <option value=''>Select an option</option> : null}
        {field.options.map((option) => (
          <option key={option.id} value={option.id}>
            {option.label}
          </option>
        ))}
      </select>
    )
  }
  if (field.type === 'combobox') {
    return (
      <input
        disabled={disabled}
        onChange={(event) => onValue(event.target.value)}
        placeholder={field.placeholder}
        value={serialized}
      />
    )
  }
  if (field.type === 'time-input') {
    return (
      <input
        disabled={disabled}
        onChange={(event) => onValue(event.target.value)}
        type='time'
        value={serialized}
      />
    )
  }
  if (numberTypes.has(field.type)) {
    return (
      <input
        disabled={disabled}
        max={field.maximum}
        min={field.minimum}
        onChange={(event) => onValue(event.target.value === '' ? null : event.target.valueAsNumber)}
        type='number'
        value={typeof value === 'number' ? value : ''}
      />
    )
  }
  if (textTypes.has(field.type)) {
    return (
      <input
        disabled={disabled}
        onChange={(event) => onValue(event.target.value)}
        placeholder={field.placeholder}
        value={serialized}
      />
    )
  }
  if (field.type === 'dropdown') {
    return (
      <input
        disabled={disabled}
        onChange={(event) => onValue(event.target.value)}
        placeholder={field.placeholder ?? 'Enter a resource ID'}
        value={serialized}
      />
    )
  }
  if (longTextTypes.has(field.type)) {
    return (
      <textarea
        disabled={disabled}
        onChange={(event) => onValue(event.target.value)}
        placeholder={field.placeholder}
        rows={field.type === 'code' ? 8 : 4}
        value={serialized}
      />
    )
  }
  if (structuredTypes.has(field.type)) {
    return (
      <Suspense fallback={<small>Loading visual builder…</small>}>
        <EditorStructuredField
          disabled={disabled}
          fieldType={field.type}
          onError={onError}
          onValue={onValue}
          value={value}
        />
      </Suspense>
    )
  }
  if (jsonTypes.has(field.type)) {
    return (
      <textarea
        disabled={disabled}
        onBlur={() => {
          try {
            onValue(draft.trim() ? (JSON.parse(draft) as EditorTemplateJsonValue) : null)
            onError(null)
          } catch {
            onError(`${field.title} must contain valid JSON`)
          }
        }}
        onChange={(event) => setDraft(event.target.value)}
        rows={5}
        value={draft}
      />
    )
  }
  return <small>Use the advanced editor for this field type: {field.type}</small>
}

function fieldValue(workflow: EditorWorkflow, blockId: string, fieldId: string): unknown {
  const field = workflow.state.blocks[blockId]?.subBlocks[fieldId]
  return field && typeof field === 'object' && !Array.isArray(field) && 'value' in field
    ? field.value
    : null
}

function conditionMatches(condition: unknown, workflow: EditorWorkflow, blockId: string): boolean {
  if (!condition || typeof condition !== 'object' || Array.isArray(condition)) return true
  const record = condition as Record<string, unknown>
  if (typeof record.field !== 'string') return true
  const current = fieldValue(workflow, blockId, record.field)
  const expected = record.value
  let matches = Array.isArray(expected) ? expected.includes(current) : current === expected
  if (record.not === true) matches = !matches
  if (record.and) matches = matches && conditionMatches(record.and, workflow, blockId)
  if (record.or) matches = matches || conditionMatches(record.or, workflow, blockId)
  return matches
}

export function EditorBasicFields({
  blockId,
  mode = 'basic',
  onChange,
  onError,
  workflow,
}: EditorBasicFieldsProps) {
  const block = workflow.state.blocks[blockId]
  const [template, setTemplate] = useState<EditorBlockTemplateV1 | null | undefined>(undefined)

  useEffect(() => {
    let active = true
    if (!block) {
      setTemplate(null)
      return () => {
        active = false
      }
    }
    void loadEditorBlockTemplate(block.type)
      .then((loaded) => {
        if (active) setTemplate(loaded ?? null)
      })
      .catch(() => {
        if (active) setTemplate(null)
      })
    return () => {
      active = false
    }
  }, [block])

  if (!block) return null
  if (template === undefined) return <small>Loading safe field template…</small>
  if (template === null) {
    return <small>This block requires the advanced editor for configuration.</small>
  }

  const fields = template.fields.filter(
    (field) =>
      (mode === 'all' || field.mode === mode) &&
      conditionMatches(field.condition, workflow, blockId)
  )
  if (fields.length === 0) return <small>This block has no {mode} fields.</small>

  return (
    <div className='editor-basic-fields'>
      {fields.map((field) => {
        const state = block.subBlocks[field.id]
        const value =
          state && typeof state === 'object' && !Array.isArray(state) && 'value' in state
            ? state.value
            : null
        return (
          <div className='editor-basic-field' key={field.id}>
            <span>
              {field.title}
              {field.required ? ' *' : ''}
            </span>
            <FieldControl
              blockId={blockId}
              disabled={workflow.locked || block.locked === true || field.readOnly === true}
              field={field}
              templateFields={template.fields}
              onError={onError}
              onValue={(nextValue) => {
                try {
                  onChange(updateEditorSubBlockValue(workflow, blockId, field.id, nextValue))
                  onError(null)
                } catch (caught) {
                  onError(caught instanceof Error ? caught.message : 'Unable to update field')
                }
              }}
              value={value}
              workflow={workflow}
            />
          </div>
        )
      })}
    </div>
  )
}
